import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

type Lang = "en" | "am";
type Theme = "light" | "dark";

type Dict = Record<string, string>;

const EN: Dict = {
  // Nav / global
  "nav.home": "Home",
  "nav.about": "About",
  "nav.services": "Services",
  "nav.industries": "Industries",
  "nav.facilities": "Facilities",
  "nav.sustainability": "Sustainability",
  "nav.clients": "Clients",
  "nav.contact": "Contact",
  "nav.cta": "Book Inspection",
  "nav.language": "Language",
  "nav.theme": "Theme",
  "nav.toggleMenu": "Toggle menu",
  "nav.mobileNav": "Mobile navigation",
  "common.learnMore": "Learn more ↗",
  "common.requestService": "Request service ↗",
  "common.discussSector": "Discuss this sector ↗",

  // Home
  "home.hero.label": "Automotive Fleet Services PLC — Est. 1999",
  "home.hero.h1a": "Driven by excellence.",
  "home.hero.h1b": "Committed to service.",
  "home.hero.p": "Ethiopia's leading automotive fleet management, vehicle maintenance and technical service provider — for government, UN, NGO, diplomatic, and private-sector fleets.",
  "home.hero.ctaRequest": "Request Service",
  "home.hero.ctaExplore": "Explore Services",
  "home.kpi.years": "Years Experience",
  "home.kpi.facility": "Service Facility",
  "home.kpi.vehicles": "Vehicles Serviced",
  "home.kpi.support": "Emergency Support",
  "home.trusted.label": "Trusted By",
  "home.trusted.un": "UNITED NATIONS",
  "home.trusted.ngo": "NGO PARTNERS",
  "home.trusted.ins": "INSURANCE GROUPS",
  "home.trusted.gov": "GOVT. OF ETHIOPIA",
  "home.trusted.dip": "DIPLOMATIC MISSIONS",
  "home.services.h2a": "Full lifecycle fleet",
  "home.services.h2b": "capability.",
  "home.services.p": "Eight core service lines, one accountable workshop.",
  "home.svc.01.t": "Preventive Maintenance", "home.svc.01.d": "Scheduled servicing built on manufacturer intervals.",
  "home.svc.02.t": "Corrective Repairs", "home.svc.02.d": "Full mechanical and structural repair capability.",
  "home.svc.03.t": "Engine Overhaul", "home.svc.03.d": "Complete teardown, rebuild, and verification.",
  "home.svc.04.t": "Electrical Diagnostics", "home.svc.04.d": "Computerized fault-tracing with modern scan tools.",
  "home.svc.05.t": "EV Maintenance", "home.svc.05.d": "High-voltage tooling and EV battery diagnostics.",
  "home.svc.06.t": "Body & Paint", "home.svc.06.d": "Enclosed, filtered booths and precision panel repair.",
  "home.svc.07.t": "Spare Parts", "home.svc.07.d": "Genuine, OEM-approved sourcing and tracking.",
  "home.svc.08.t": "Roadside Assistance", "home.svc.08.d": "Mobile garage units dispatched to the vehicle.",
  "home.why.label": "Why Choose AFS",
  "home.why.h3a": "Proven experience,",
  "home.why.h3b": "built for premium fleets.",
  "home.why.p": "Two decades of technical expertise, a modern 3,000+ m² facility, genuine parts and a skilled team ready for the EV era — with fast, transparent turnaround.",
  "home.why.imgCaption": "Modern Workshop — Addis Ababa",
  "home.strat.label": "Accelerate Strategy",
  "home.strat.h3a": "Six pillars,",
  "home.strat.h3b": "one long-term vision.",
  "home.strat.p": "People & technical excellence, digital transformation, operational excellence, customer-centric service, strategic partnerships, and sustainability & future mobility.",
  "home.strat.imgCaption": "Accelerate Strategy 2026",
  "home.strat.link": "Explore our strategy ↗",
  "home.ev.label": "The Electric Era",
  "home.ev.h2a": "Ready for the",
  "home.ev.h2b": "electric fleet.",
  "home.ev.p": "A dedicated EV maintenance center with high-voltage tooling and specialized battery and electrical-system diagnostics — engineered for the vehicles Ethiopia will drive next.",
  "home.ev.link": "Learn about EV readiness ↗",
  "home.quotes.label": "Client Voices",
  "home.quotes.h2a": "What our",
  "home.quotes.h2b": "clients say.",
  "home.quotes.lead": "Fleet leaders across UN agencies, development partners, insurance and government share their experience partnering with AFS.",
  "home.quotes.scrollHint": "Scroll or use arrows to read more",
  "home.quotes.swipeHint": "Swipe to read more →",
  "home.quotes.dotsLabel": "Testimonial slides",
  "home.quotes.goTo": "Go to testimonial",
  "home.quotes.prev": "Previous testimonial",
  "home.quotes.next": "Next testimonial",
  "home.q1.initials": "DT",
  "home.q1.name": "Daniel T.",
  "home.q1.role": "Fleet Manager",
  "home.q1.org": "United Nations Agency",
  "home.q1.text": "Reliable turnaround and transparent reporting — AFS keeps our fleet mission-ready across the country.",
  "home.q2.initials": "HK",
  "home.q2.name": "Helen K.",
  "home.q2.role": "Operations Lead",
  "home.q2.org": "International Development Partner",
  "home.q2.text": "Genuine parts, disciplined job-card process, and a technical team that clearly knows heavy-duty vehicles.",
  "home.q3.initials": "MR",
  "home.q3.name": "Michael R.",
  "home.q3.role": "Claims Manager",
  "home.q3.org": "Regional Insurance Group",
  "home.q3.text": "Fast claims turnaround and clear cost estimation — a dependable partner for our insured fleet repairs.",
  "home.q4.initials": "SA",
  "home.q4.name": "Solomon A.",
  "home.q4.role": "Director of Transport",
  "home.q4.org": "Federal Government of Ethiopia",
  "home.q4.text": "AFS delivers the accountability and technical depth we require for national fleet operations at scale.",
  "home.q5.initials": "LN",
  "home.q5.name": "Laura N.",
  "home.q5.role": "Embassy Transport Coordinator",
  "home.q5.org": "Diplomatic Mission, Addis Ababa",
  "home.q5.text": "Discreet, punctual and impeccably documented — exactly the standard our mission expects from a fleet partner.",
  "home.cta.h2a": "Ready to keep your fleet",
  "home.cta.h2b": "moving?",
  "home.cta.book": "Book Inspection",
  "home.cta.view": "View Services",

  // Corporate home (Geotab-style)
  "home.geo.h1": "One platform for optimal fleet performance",
  "home.geo.b1": "Connect your entire fleet, seamlessly",
  "home.geo.b2": "Unlock workshop intelligence with digital job cards",
  "home.geo.b3": "Drive safety, efficiency, and savings",
  "home.geo.ctaPrimary": "Get a demo",
  "home.geo.ctaSecondary": "Platform overview",
  "home.geo.nav.why": "Why AFS",
  "home.geo.nav.trusted": "Trusted partners",
  "home.geo.nav.services": "Fleet solutions",
  "home.geo.nav.industries": "Industries",
  "home.geo.nav.stories": "Success stories",
  "home.geo.nav.support": "24/7 support",
  "home.geo.product.label": "Product",
  "home.geo.product.h2": "EV maintenance center",
  "home.geo.product.p": "A dedicated EV maintenance center with high-voltage tooling and specialized battery and electrical-system diagnostics — engineered for the vehicles Ethiopia will drive next.",
  "home.geo.product.link": "Learn more",
  "home.geo.pillars.label": "Fleet operations",
  "home.geo.pillars.h2": "Put connected fleet intelligence to work",
  "home.geo.pillars.sub": "An integrated workshop for safe, sustainable and cost-effective fleet mobility powered by data and technical excellence.",
  "home.geo.pillar.1.t": "Reduce costs",
  "home.geo.pillar.1.d": "Automate preventive schedules and be proactively alerted to maintenance opportunities that lower costs and optimize uptime.",
  "home.geo.pillar.1.link": "Learn more about fleet productivity",
  "home.geo.pillar.2.t": "Enhance safety",
  "home.geo.pillar.2.d": "Driver-focused inspections, HSE-compliant workshop practices, and rigorous quality checks minimize risk across your fleet.",
  "home.geo.pillar.2.link": "Learn more about fleet safety",
  "home.geo.pillar.3.t": "Leverage data advantage",
  "home.geo.pillar.3.d": "Digital job cards, transparent reporting, and computerized diagnostics simplify complex fleet data for smarter decisions.",
  "home.geo.pillar.3.link": "Learn more about digital operations",
  "home.geo.pillar.4.t": "Maintain your fleet",
  "home.geo.pillar.4.d": "Stay ahead with automated reminders and integrated maintenance — identify and prioritize tasks early to reduce downtime.",
  "home.geo.pillar.4.link": "Learn more about fleet maintenance",
  "home.geo.pillar.5.t": "Expand value",
  "home.geo.pillar.5.d": "From EV readiness to roadside assistance — extend AFS capability across your full fleet lifecycle from one accountable partner.",
  "home.geo.pillar.5.link": "Learn more about expandability",
  "home.geo.excellence.label": "Why businesses choose AFS",
  "home.geo.excellence.h2": "25+ years of fleet management excellence",
  "home.geo.excellence.link": "Why choose AFS",
  "home.geo.excellence.stories": "Success stories",
  "home.geo.solutions.h2": "Fleet operations powered by technical excellence",
  "home.geo.solutions.seeAll": "See all solutions",
  "home.geo.industries.h2": "Fleet management solutions tailored to your industry",
  "home.geo.industries.seeAll": "See all industries",
  "home.geo.demo.h2": "Fleet management demo",
  "home.geo.demo.p": "Walk our workshop, meet our lead engineers, and see the systems trusted by UN, diplomatic and enterprise fleets across Addis Ababa.",
  "home.geo.demo.cta": "Get a demo today",

  // About
  "about.hero.label": "About AFS",
  "about.hero.h1a": "Company story,",
  "about.hero.h1b": "history & leadership.",
  "about.story.label": "Our Story",
  "about.story.h3": "Founded 1999. Renewed for a new era.",
  "about.story.p1a": "AFS was established in ",
  "about.story.p1b": "October 1999",
  "about.story.p1c": ", following the restructuring of the former JTO under the DDPC, to meet Ethiopia's growing need for integrated fleet management and technical support.",
  "about.story.p2a": "Today the company operates a modern ",
  "about.story.p2b": "3,000+ m² facility",
  "about.story.p2c": " in Addis Ababa, supported by mobile service units — serving government, UN agencies, NGOs, diplomatic missions, and private clients.",
  "about.story.p3a": "80% of company shares",
  "about.story.p3b": " are held by Ato Zelalem Lemi, leading a full modernization program across governance, talent, and technology.",
  "about.mvv.mission": "Mission",
  "about.mvv.missionP": "Deliver comprehensive automotive and fleet management solutions that enable clients to operate safely, efficiently, and cost-effectively.",
  "about.mvv.vision": "Vision",
  "about.mvv.visionP": "Ethiopia's premier provider of integrated automotive, fleet management, and sustainable mobility solutions.",
  "about.mvv.values": "Core Values",
  "about.mvv.valuesP": "Integrity · Customer Focus · Excellence · Innovation · Professionalism · Safety · Teamwork · Accountability · Sustainability · Continuous Improvement",
  "about.time.h2a": "Timeline of",
  "about.time.h2b": "transformation.",
  "about.time.r1.t": "Founded",
  "about.time.r1.d": "Established following restructuring of the former JTO under the DDPC.",
  "about.time.r2.y": "1999–2025",
  "about.time.r2.t": "Two decades of growth",
  "about.time.r2.d": "Built a trusted reputation across government, UN, NGO, and diplomatic fleet servicing.",
  "about.time.r3.t": "Strategic transformation",
  "about.time.r3.d": "80% of shares acquired by Ato Zelalem Lemi; modernization of governance, systems, and EV capability begins.",
  "about.lead.h2": "Leadership.",
  "about.lead.label": "Majority Shareholder — 80%",
  "about.lead.name": "Ato Zelalem Lemi",
  "about.lead.p": "A seasoned automotive-industry investor with over two decades of experience, leading AFS's modernization program — strengthening governance, integrating skilled professionals, and expanding strategic partnerships across the sector.",
  "about.pill.h2a": "Accelerate Strategy —",
  "about.pill.h2b": "six pillars.",
  "about.pill.01.t": "People & Technical Excellence", "about.pill.01.d": "Continuous professional development and technical certification.",
  "about.pill.02.t": "Innovation & Digital Transformation", "about.pill.02.d": "Advanced diagnostics, digital fleet systems, EV services.",
  "about.pill.03.t": "Operational Excellence", "about.pill.03.d": "Standardized procedures and quality assurance.",
  "about.pill.04.t": "Customer-Centric Service", "about.pill.04.d": "Solutions tailored to each client's operational needs.",
  "about.pill.05.t": "Strategic Partnerships", "about.pill.05.d": "Deepening ties with government, UN, insurers, manufacturers.",
  "about.pill.06.t": "Sustainability & Future Mobility", "about.pill.06.d": "EV readiness and energy-efficient green mobility investment.",

  // Services
  "services.hero.label": "Services",
  "services.hero.h1a": "Every service your",
  "services.hero.h1b": "fleet needs.",
  "services.r1.label": "Fleet Management", "services.r1.t1": "End-to-end", "services.r1.t2": "fleet lifecycle.", "services.r1.body": "Fleet inspection, reporting, and performance monitoring that extends asset life and reduces cost.", "services.r1.cap": "Fleet Management",
  "services.r2.label": "Preventive Maintenance", "services.r2.t1": "Stay ahead of", "services.r2.t2": "breakdowns.", "services.r2.body": "Scheduled servicing, fluid management, brake and suspension checks — around manufacturer intervals and real fleet usage.", "services.r2.cap": "Preventive Maintenance",
  "services.r3.label": "Repairs", "services.r3.t1": "Corrective repair,", "services.r3.t2": "done right.", "services.r3.body": "Mechanical, structural, and engine-overhaul work under a controlled job-card process with multi-level quality inspection.", "services.r3.cap": "Repairs & Engine Overhaul",
  "services.r4.label": "Diagnostics", "services.r4.t1": "Computerized", "services.r4.t2": "precision.", "services.r4.body": "Modern electronic diagnosers and analyzers identify faults fast — minimizing guesswork and repeat visits.", "services.r4.cap": "Electrical & Electronic Diagnostics",
  "services.r5.label": "Body & Paint", "services.r5.t1": "Structural repair,", "services.r5.t2": "factory finish.", "services.r5.body": "Enclosed, filtered paint booths and panel work that restores both appearance and structural integrity.", "services.r5.cap": "Body & Paint",
  "services.r6.label": "EV Service", "services.r6.t1": "Ready for the", "services.r6.t2": "electric fleet.", "services.r6.body": "Dedicated EV maintenance center with high-voltage tooling and specialized battery and electrical diagnostics.", "services.r6.cap": "EV Maintenance Center",

  // Industries
  "ind.hero.label": "Industries",
  "ind.hero.h1a": "Six sectors.",
  "ind.hero.h1b": "One accountable workshop.",
  "ind.hero.lead": "From UN motor pools to construction fleets — AFS delivers specialized, audit-ready service standards tuned to each sector.",
  "ind.sectorLabel": "Sector",
  "ind.s1.tag": "Government", "ind.s1.t1": "Public sector", "ind.s1.t2": "fleets.", "ind.s1.lead": "Federal and regional administrations kept mission-ready.", "ind.s1.body": "From ministerial motor pools to regional transport bureaus, we maintain public-sector vehicles under strict compliance, audit-ready reporting, and predictable service intervals.", "ind.s1.b1": "Ministerial motor pools", "ind.s1.b2": "Regional bureaus", "ind.s1.b3": "Municipal utilities", "ind.s1.m1": "Uptime SLA", "ind.s1.m2": "Avg. TAT",
  "ind.s2.tag": "NGO", "ind.s2.t1": "Development", "ind.s2.t2": "partners.", "ind.s2.lead": "Dependable field-tested maintenance for humanitarian operations.", "ind.s2.body": "We service 4x4 and heavy-duty vehicles used in the field — with parts availability, road-worthiness certification, and technical crews trained on Toyota, Nissan, Land Rover and Isuzu platforms.", "ind.s2.b1": "4×4 field vehicles", "ind.s2.b2": "Road-worthiness certification", "ind.s2.b3": "Nationwide dispatch", "ind.s2.m1": "NGO Clients", "ind.s2.m2": "Field-ready",
  "ind.s3.tag": "UN Agencies", "ind.s3.t1": "International", "ind.s3.t2": "development.", "ind.s3.lead": "Rigid adherence to global service and safety standards.", "ind.s3.body": "Trusted by UNDP, UNICEF, WHO, WFP and FAO — our processes match international procurement, HSE and reporting requirements, backed by digital job cards and traceable parts sourcing.", "ind.s3.b1": "Digital job cards", "ind.s3.b2": "Traceable OEM parts", "ind.s3.b3": "HSE-compliant workshop", "ind.s3.m1": "UN Agencies", "ind.s3.m2": "ISO alignment",
  "ind.s4.tag": "Insurance", "ind.s4.t1": "Claims &", "ind.s4.t2": "underwriting.", "ind.s4.lead": "Transparent, digitized cost estimation with rapid turnaround.", "ind.s4.body": "Approved by leading Ethiopian insurers for accident repair, we deliver itemized estimates, photographic evidence and structured claims workflow — cutting cycle time and dispute volume.", "ind.s4.b1": "Itemized digital estimates", "ind.s4.b2": "Photographic claim evidence", "ind.s4.b3": "Approved body & paint", "ind.s4.m1": "Insurers", "ind.s4.m2": "Est. cycle",
  "ind.s5.tag": "Corporate", "ind.s5.t1": "Commercial &", "ind.s5.t2": "logistics.", "ind.s5.lead": "Scheduled maintenance that prevents supply-chain downtime.", "ind.s5.body": "Distribution fleets, sales fleets and logistics operators run on preventive schedules that we manage end-to-end — from mileage tracking to tire, brake and drivetrain lifecycle planning.", "ind.s5.b1": "Distribution fleets", "ind.s5.b2": "Sales fleets", "ind.s5.b3": "Cold-chain logistics", "ind.s5.m1": "Vehicles / yr", "ind.s5.m2": "PM adherence",
  "ind.s6.tag": "Construction", "ind.s6.t1": "Industrial", "ind.s6.t2": "operations.", "ind.s6.lead": "Heavy-duty repair for demanding field conditions.", "ind.s6.body": "Diesel light-truck servicing, hydraulic system checks, chassis welding and structural repair for construction, mining and infrastructure operators working across Ethiopia's toughest terrain.", "ind.s6.b1": "Diesel light-truck service", "ind.s6.b2": "Chassis & structural welding", "ind.s6.b3": "Hydraulic diagnostics", "ind.s6.m1": "Truck bays", "ind.s6.m2": "Weld capacity",
  "ind.cap.label": "Cross-sector capability",
  "ind.cap.h2a": "One workshop.",
  "ind.cap.h2b": "Every fleet profile.",
  "ind.cap.desc": "Whether it's a diplomatic sedan, a humanitarian 4×4, an insured accident recovery, or a construction truck — the same engineering discipline, the same digital job-card process.",
  "ind.cap.s1": "Years serving fleets",
  "ind.cap.s2": "Vehicles per year",
  "ind.cap.s3": "Institutional clients",
  "ind.cap.s4": "Facility footprint",
  "ind.cap.talk": "Talk to our fleet team ↗",
  "ind.cap.explore": "Explore capabilities",

  // Facilities
  "fac.hero.label": "Facilities",
  "fac.hero.h1a": "3,000+ m² of",
  "fac.hero.h1b": "engineered capacity.",
  "fac.hero.lead": "Gotera, Nefas Silk Lafto Sub-city, Addis Ababa.",
  "fac.show.h2a": "Facility",
  "fac.show.h2b": "showcase.",
  "fac.eq.h2a": "Key",
  "fac.eq.h2b": "equipment.",
  "fac.eq.01.t": "Four-post lifts", "fac.eq.01.d": "8,000–12,000 lb capacity · 4 bays plus inspection pits",
  "fac.eq.02.t": "Electronic diagnosers", "fac.eq.02.d": "Autoboss & Launch (2021) · 23 units",
  "fac.eq.03.t": "Welding machines", "fac.eq.03.d": "3 units for structural and body repair",
  "fac.eq.04.t": "Multimeters & analyzers", "fac.eq.04.d": "3 electronic diagnostic analyzers",
  "fac.eq.05.t": "Safety systems", "fac.eq.05.d": "Fire extinguishers, first aid kits, fire blankets",

  // Sustainability
  "sus.hero.label": "Sustainability",
  "sus.hero.h1a": "Safe operations.",
  "sus.hero.h1b": "Sustainable growth.",
  "sus.r.01.t": "Health, Safety & Environmental (HSE) Policy", "sus.r.01.d": "PPE protocols, engineered safety zones, and continuous risk assessment across the facility.",
  "sus.r.02.t": "Environmental Protection Policy", "sus.r.02.d": "Proper disposal of used oil, lubricants, and lead-acid batteries; controlled chemical storage.",
  "sus.r.03.t": "Waste Management", "sus.r.03.d": "Waste segregation, spill prevention, and clean workshop management.",
  "sus.r.04.t": "EV Readiness", "sus.r.04.d": "High-voltage tooling, dedicated EV maintenance areas, and battery-safety training.",
  "sus.r.05.t": "Sustainability Commitment", "sus.r.05.d": "Energy-efficient equipment, reduced paper dependency via digital job-card tracking.",

  // Clients
  "cli.hero.label": "Clients",
  "cli.hero.h1a": "Institutions that",
  "cli.hero.h1b": "trust AFS.",
  "cli.trust.label": "Trusted Partners",
  "cli.trust.h2a": "40+ institutions across",
  "cli.trust.h2b": "UN, government, NGO and insurance sectors.",
  "cli.note": "Every logo represents a long-standing institutional partnership across UN agencies, diplomatic missions, NGOs, insurance and government sectors.",
  "cli.trust.count": "institutional partners",

  // Contact
  "con.hero.label": "Contact",
  "con.hero.h1a": "Book an",
  "con.hero.h1b": "inspection.",
  "con.hero.lead": "Get in touch with the AFS team.",
  "con.form.label": "Send a Message",
  "con.form.name": "Full Name", "con.form.namePh": "Your name",
  "con.form.org": "Organization", "con.form.orgPh": "Company / Agency",
  "con.form.email": "Email", "con.form.emailPh": "you@organization.org",
  "con.form.msg": "Message", "con.form.msgPh": "Tell us about your fleet needs",
  "con.form.submit": "Submit Request",
  "con.form.thanks": "Thanks — we'll be in touch shortly.",
  "con.info.label": "Get In Touch",
  "con.info.location": "Location",
  "con.info.locationV": "Gotera, Nefas Silk Lafto Sub-city, Addis Ababa, Ethiopia",
  "con.info.phone": "Phone",
  "con.info.email": "Email",
  "con.info.hours": "Workshop Hours",
  "con.info.hoursV": "Mon–Sat, 8:00 AM – 6:00 PM · Emergency 24/7",
  "con.info.map": "Gotera, Addis Ababa",

  // Footer
  "foot.desc": "Ethiopia's premier automotive fleet management and technical service provider since 1999.",
  "foot.company": "Company",
  "foot.services": "Services",
  "foot.contact": "Contact",
  "foot.link.about": "About",
  "foot.link.sustainability": "Sustainability",
  "foot.link.clients": "Clients",
  "foot.link.fleet": "Fleet Management",
  "foot.link.ev": "EV Maintenance",
  "foot.link.facilities": "Facilities",
  "foot.addr1": "Gotera, Nefas Silk Lafto",
  "foot.addr2": "Addis Ababa, Ethiopia",
  "foot.copyright": "© 2026 AFS International PLC. All rights reserved.",
  "foot.est": "Est. 1999 · Addis Ababa",
};

const AM: Dict = {
  "nav.home": "መነሻ",
  "nav.about": "ስለ እኛ",
  "nav.services": "አገልግሎቶች",
  "nav.industries": "ኢንዱስትሪዎች",
  "nav.facilities": "ተቋማት",
  "nav.sustainability": "ዘላቂነት",
  "nav.clients": "ደንበኞች",
  "nav.contact": "ያግኙን",
  "nav.cta": "ምርመራ ይመዝገቡ",
  "nav.language": "ቋንቋ",
  "nav.theme": "ገጽታ",
  "nav.toggleMenu": "ምናሌ ቀያይር",
  "nav.mobileNav": "የሞባይል ዝርዝር",
  "common.learnMore": "ተጨማሪ ይመልከቱ ↗",
  "common.requestService": "አገልግሎት ይጠይቁ ↗",
  "common.discussSector": "ስለዚህ ዘርፍ ይነጋገሩ ↗",

  // Home
  "home.hero.label": "አውቶሞቲቭ ፍሊት ሰርቪስስ ኃ.የተ.የግ.ማ — የተመሠረተ 1999",
  "home.hero.h1a": "በምርጥነት የተመራ።",
  "home.hero.h1b": "ለአገልግሎት ቁርጠኛ።",
  "home.hero.p": "የኢትዮጵያ ቀዳሚ የተሽከርካሪ ፍሊት አስተዳደር፣ ጥገና እና ቴክኒካል አገልግሎት አቅራቢ — ለመንግስት፣ ለተባበሩት መንግስታት፣ ለበጎ አድራጎት፣ ለዲፕሎማቲክ እና ለግል ዘርፍ ፍሊቶች።",
  "home.hero.ctaRequest": "አገልግሎት ይጠይቁ",
  "home.hero.ctaExplore": "አገልግሎቶችን ይዳስሱ",
  "home.kpi.years": "የሙያ ዓመታት",
  "home.kpi.facility": "የአገልግሎት ቦታ",
  "home.kpi.vehicles": "የተስተናገዱ ተሽከርካሪዎች",
  "home.kpi.support": "የአስቸኳይ ድጋፍ",
  "home.trusted.label": "የሚያምኑት",
  "home.trusted.un": "የተባበሩት መንግስታት",
  "home.trusted.ngo": "የበጎ አድራጎት አጋሮች",
  "home.trusted.ins": "የኢንሹራንስ ቡድኖች",
  "home.trusted.gov": "የኢትዮጵያ መንግስት",
  "home.trusted.dip": "የዲፕሎማቲክ ተልእኮዎች",
  "home.services.h2a": "የተሟላ የፍሊት",
  "home.services.h2b": "አቅም።",
  "home.services.p": "ስምንት ዋና የአገልግሎት መስመሮች፣ አንድ ተጠያቂ አውደ ጥገና።",
  "home.svc.01.t": "የመከላከያ ጥገና", "home.svc.01.d": "በአምራች መርሃ ግብር መሠረት የተያዘ አገልግሎት።",
  "home.svc.02.t": "የማስተካከያ ጥገና", "home.svc.02.d": "ሙሉ ሜካኒካል እና መዋቅራዊ የጥገና አቅም።",
  "home.svc.03.t": "የሞተር ማደስ", "home.svc.03.d": "ሙሉ መፍታት፣ መገንባት እና ማረጋገጥ።",
  "home.svc.04.t": "የኤሌክትሪክ ምርመራ", "home.svc.04.d": "ዘመናዊ የስካን መሳሪያዎችን በመጠቀም ችግር መለየት።",
  "home.svc.05.t": "የኤሌክትሪክ ተሽከርካሪ ጥገና", "home.svc.05.d": "ከፍተኛ ቮልቴጅ መሳሪያዎች እና የEV ባትሪ ምርመራ።",
  "home.svc.06.t": "አካል እና ቀለም", "home.svc.06.d": "የተዘጋ የቀለም መርጨት ክፍል እና ጥራት ያለው ጥገና።",
  "home.svc.07.t": "የመለዋወጫ እቃዎች", "home.svc.07.d": "ኦሪጅናል፣ በOEM የተፈቀደ አቅርቦት እና ክትትል።",
  "home.svc.08.t": "የመንገድ ላይ እርዳታ", "home.svc.08.d": "ወደ ተሽከርካሪው የሚላኩ ተንቀሳቃሽ የጥገና ክፍሎች።",
  "home.why.label": "AFSን ለምን ይመርጣሉ",
  "home.why.h3a": "የተረጋገጠ ልምድ፣",
  "home.why.h3b": "ለከፍተኛ ፍሊቶች የተዘጋጀ።",
  "home.why.p": "ሁለት አስርት ዓመታት የቴክኒክ ልምድ፣ ዘመናዊ 3,000+ ካሬ ሜትር ተቋም፣ ኦሪጅናል ዕቃዎች እና ለEV ዘመን የተዘጋጀ ሙያተኛ ቡድን — ፈጣን እና ግልፅ አገልግሎት።",
  "home.why.imgCaption": "ዘመናዊ አውደ ጥገና — አዲስ አበባ",
  "home.strat.label": "አክሰለሬት ስትራቴጂ",
  "home.strat.h3a": "ስድስት ምሰሶዎች፣",
  "home.strat.h3b": "አንድ የረጅም ጊዜ ራዕይ።",
  "home.strat.p": "ሰዎች እና ቴክኒካል ብቃት፣ ዲጂታል ለውጥ፣ የስራ ብቃት፣ ደንበኛ-ተኮር አገልግሎት፣ ስትራቴጂካዊ ሽርክናዎች እና ዘላቂነት እና የወደፊት ተንቀሳቃሽነት።",
  "home.strat.imgCaption": "አክሰለሬት ስትራቴጂ 2026",
  "home.strat.link": "ስትራቴጂያችንን ይዳስሱ ↗",
  "home.ev.label": "የኤሌክትሪክ ዘመን",
  "home.ev.h2a": "ለኤሌክትሪክ",
  "home.ev.h2b": "ፍሊት ዝግጁ።",
  "home.ev.p": "የተለየ የEV ጥገና ማዕከል ከከፍተኛ ቮልቴጅ መሳሪያዎች እና ልዩ የባትሪ እና የኤሌክትሪክ ስርዓት ምርመራ ጋር — ኢትዮጵያ ወደፊት ለምትነዳቸው ተሽከርካሪዎች የተነደፈ።",
  "home.ev.link": "ስለ EV ዝግጁነት ይማሩ ↗",
  "home.quotes.label": "የደንበኛ ድምፆች",
  "home.quotes.h2a": "ደንበኞቻችን",
  "home.quotes.h2b": "ምን ይላሉ።",
  "home.quotes.lead": "በተባበሩት መንግስታት፣ በልማት አጋሮች፣ በኢንሹራንስ እና በመንግስት ፍሊት አመራሮች ከAFS ጋር ያላቸውን ልምድ ያጋሩ።",
  "home.quotes.scrollHint": "ተጨማሪ ለማንበብ ይሸብልሉ ወይም ቀስቶችን ይጠቀሙ",
  "home.quotes.swipeHint": "ለማንበብ ይጎትቱ →",
  "home.quotes.dotsLabel": "የምስክርነት ስላይዶች",
  "home.quotes.goTo": "ወደ ምስክርነት ይሂዱ",
  "home.quotes.prev": "ቀዳሚ ምስክርነት",
  "home.quotes.next": "ቀጣይ ምስክርነት",
  "home.q1.initials": "DT",
  "home.q1.name": "ዳንኤል ቲ.",
  "home.q1.role": "የፍሊት ሥራ አስኪያጅ",
  "home.q1.org": "የተባበሩት መንግስታት ኤጀንሲ",
  "home.q1.text": "አስተማማኝ የመመለሻ ጊዜ እና ግልፅ ሪፖርት — AFS ፍሊታችንን በመላ አገሪቱ ዝግጁ ያደርገዋል።",
  "home.q2.initials": "HK",
  "home.q2.name": "ሄለን ኬ.",
  "home.q2.role": "የስራ አስተባባሪ",
  "home.q2.org": "ዓለም አቀፍ የልማት አጋር",
  "home.q2.text": "ኦሪጅናል ዕቃዎች፣ ተግሣጽ ያለው የስራ ሂደት እና ከባድ ተሽከርካሪዎችን በደንብ የሚያውቅ ቴክኒካል ቡድን።",
  "home.q3.initials": "MR",
  "home.q3.name": "ማይክል አር.",
  "home.q3.role": "የክሌም ሥራ አስኪያጅ",
  "home.q3.org": "ክልላዊ የኢንሹራንስ ቡድን",
  "home.q3.text": "ፈጣን የክሌም አገልግሎት እና ግልፅ የወጪ ግምት — ለተጠበቀው ፍሊታችን አስተማማኝ አጋር።",
  "home.q4.initials": "SA",
  "home.q4.name": "ሰለሞን አ.",
  "home.q4.role": "የትራንስፖርት ዳይሬክተር",
  "home.q4.org": "የኢትዮጵያ ፌዴራል መንግስት",
  "home.q4.text": "AFS ለብሔራዊ ፍሊት ክወና በሰፊው የምንፈልገውን ተጠያቂነት እና ቴክኒካል ጥልቀት ያቀርባል።",
  "home.q5.initials": "LN",
  "home.q5.name": "ላውራ ኤን.",
  "home.q5.role": "የኤምባሲ ትራንስፖርት አስተባባሪ",
  "home.q5.org": "የዲፕሎማቲክ ተልእኮ፣ አዲስ አበባ",
  "home.q5.text": "ደብዛዛ፣ ጊዜያዊ እና በጥሩ ሁኔታ የተመዘገበ — ተልእኳችን ከፍሊት አጋር የሚጠብቀው ደረጃ በትክክል።",
  "home.cta.h2a": "ፍሊትዎን በእንቅስቃሴ ላይ ለማቆየት",
  "home.cta.h2b": "ዝግጁ ነዎት?",
  "home.cta.book": "ምርመራ ይመዝገቡ",
  "home.cta.view": "አገልግሎቶችን ይመልከቱ",

  "home.geo.h1": "ለተመቻቸ የፍሊት አፈጻጸም አንድ መድረክ",
  "home.geo.b1": "መላውን ፍሊትዎን በተሳካ ሁኔታ ያገናኙ",
  "home.geo.b2": "በዲጂታል የስራ ካርዶች የአውደ ጥገና መረጃ ይክፈቱ",
  "home.geo.b3": "ደህንነት፣ ብቃት እና ቁጠባን ያሳድጉ",
  "home.geo.ctaPrimary": "ማሳያ ይጠይቁ",
  "home.geo.ctaSecondary": "የመድረክ ግምት",
  "home.geo.nav.why": "ለምን AFS",
  "home.geo.nav.trusted": "የታመኑ አጋሮች",
  "home.geo.nav.services": "የፍሊት መፍትሄዎች",
  "home.geo.nav.industries": "ኢንዱስትሪዎች",
  "home.geo.nav.stories": "የስኬት ታሪኮች",
  "home.geo.nav.support": "24/7 ድጋፍ",
  "home.geo.product.label": "ምርት",
  "home.geo.product.h2": "EV ጥገና ማዕከል",
  "home.geo.product.p": "ከፍተኛ-ቮልቴጅ መሳሪያዎች እና ልዩ የባትሪ እና የኤሌክትሪክ ስርዓት ምርመራ — ለኢትዮጵያ የሚመጡ ተሽከርካሪዎች የተነደፈ።",
  "home.geo.product.link": "ተጨማሪ ይወቁ",
  "home.geo.pillars.label": "የፍሊት ክወና",
  "home.geo.pillars.h2": "የተገናኘ የፍሊት መረጃን ለተሻለ ውጤት ይጠቀሙ",
  "home.geo.pillars.sub": "ለደህንነቱ የተረጋገጠ፣ ዘላቂ እና ወጪ-ቆጣቢ የፍሊት ተንቀሳቃሽነት የተቀናጀ አውደ ጥገና።",
  "home.geo.pillar.1.t": "ወጪን ይቀንሱ",
  "home.geo.pillar.1.d": "የመከላከያ መርሃ ግብሮችን በራስ-ሰር ያስተዳድሩ እና ወጪን የሚቀንሱ እድሎችን በACTIVE ሁኔታ ይቀበሉ።",
  "home.geo.pillar.1.link": "ስለ ፍሊት ብቃት ይወቁ",
  "home.geo.pillar.2.t": "ደህንነትን ያሳድጉ",
  "home.geo.pillar.2.d": "የሾፈር-ተኮር ምርመራዎች፣ HSE-ተከትሎ አውደ ጥገና እና ጥብቅ የጥራት ምርመራዎች አደጋን ይቀንሳሉ።",
  "home.geo.pillar.2.link": "ስለ ፍሊት ደህንነት ይወቁ",
  "home.geo.pillar.3.t": "የመረጃ ጥቅም ይውሰዱ",
  "home.geo.pillar.3.d": "ዲጂታል የስራ ካርዶች፣ ግልፅ ሪፖርቶች እና ኮምፒውተር ምርመራ ውስብስብ የፍሊት መረጃን ለብልሃዊ ውሳኔ ያቀላል።",
  "home.geo.pillar.3.link": "ስለ ዲጂታል ክወና ይወቁ",
  "home.geo.pillar.4.t": "ፍሊትዎን ይጠብቁ",
  "home.geo.pillar.4.d": "በAUTO ማስታወሻዎች እና የተቀናጀ ጥገና — ተግባሮችን ቀደም ብለው ይለዩ እና downtimeን ይቀንሱ።",
  "home.geo.pillar.4.link": "ስለ ፍሊት ጥገና ይወቁ",
  "home.geo.pillar.5.t": "እሴትን ያስፋፉ",
  "home.geo.pillar.5.d": "ከEV ዝግጁነት እስከ የመንገድ ድጋፍ — የAFS አቅምን በሙሉ የፍሊት ዑደትዎ ላይ ያስፋፉ።",
  "home.geo.pillar.5.link": "ስለ ማስፋፊያ ይወቁ",
  "home.geo.excellence.label": "ንግዶች AFSን ለምን ይመርጣሉ",
  "home.geo.excellence.h2": "25+ ዓመታት የፍሊት አስተዳደር ብቃት",
  "home.geo.excellence.link": "ለምን AFS",
  "home.geo.excellence.stories": "የስኬት ታሪኮች",
  "home.geo.solutions.h2": "በቴክኒካል ብቃት የተጎላበተ የፍሊት ክወና",
  "home.geo.solutions.seeAll": "ሁሉንም መፍትሄዎች ይመልከቱ",
  "home.geo.industries.h2": "ለኢንዱስትሪዎ ያጣጣ የፍሊት አስተዳደር መፍትሄዎች",
  "home.geo.industries.seeAll": "ሁሉንም ኢንዱስትሪዎች ይመልከቱ",
  "home.geo.demo.h2": "የፍሊት አስተዳደር ማሳያ",
  "home.geo.demo.p": "አውደ ጥገናችንን ይዞሩ፣ ዋና መሐንዚሶቻችንን ይገናኙ እና UN እና ዲፕሎማቲክ ፍሊቶች የሚያምኑባቸውን ስርዓቶች ይመልከቱ።",
  "home.geo.demo.cta": "ዛሬ ማሳያ ይጠይቁ",

  // About
  "about.hero.label": "ስለ AFS",
  "about.hero.h1a": "የኩባንያ ታሪክ፣",
  "about.hero.h1b": "ታሪክ እና አመራር።",
  "about.story.label": "ታሪካችን",
  "about.story.h3": "የተመሠረተ 1999። ለአዲስ ዘመን የታደሰ።",
  "about.story.p1a": "AFS የተመሠረተው በ",
  "about.story.p1b": "ጥቅምት 1999",
  "about.story.p1c": " ነው፣ የቀድሞው JTO ከDDPC ስር ከተዋቀረ በኋላ፣ የኢትዮጵያን እያደገ የመጣ የተቀናጀ የፍሊት አስተዳደር እና ቴክኒካል ድጋፍ ፍላጎት ለማሟላት።",
  "about.story.p2a": "ዛሬ ኩባንያው ዘመናዊ ",
  "about.story.p2b": "3,000+ ካሬ ሜትር ተቋም",
  "about.story.p2c": " በአዲስ አበባ ያንቀሳቅሳል፣ በተንቀሳቃሽ የአገልግሎት ክፍሎች የተደገፈ — ለመንግስት፣ ለተባበሩት መንግስታት፣ ለNGOs፣ ለዲፕሎማቲክ ተልእኮዎች እና ለግል ደንበኞች ያገለግላል።",
  "about.story.p3a": "80% የኩባንያ ድርሻ",
  "about.story.p3b": " በአቶ ዘላለም ለሚ ተይዟል፣ በአስተዳደር፣ በሙያ እና በቴክኖሎጂ ላይ ሙሉ የዘመናዊነት ፕሮግራም ይመራሉ።",
  "about.mvv.mission": "ተልእኮ",
  "about.mvv.missionP": "ደንበኞች በደህና፣ በብቃት እና በወጪ ቆጣቢ ሁኔታ እንዲንቀሳቀሱ የሚያስችል የተሟላ የተሽከርካሪ እና የፍሊት አስተዳደር መፍትሔዎችን ማቅረብ።",
  "about.mvv.vision": "ራዕይ",
  "about.mvv.visionP": "የኢትዮጵያ ቀዳሚ የተቀናጀ የተሽከርካሪ፣ የፍሊት አስተዳደር እና ዘላቂ ተንቀሳቃሽነት መፍትሔዎች አቅራቢ።",
  "about.mvv.values": "ዋና እሴቶች",
  "about.mvv.valuesP": "ታማኝነት · ደንበኛ ትኩረት · ብቃት · ፈጠራ · ሙያዊነት · ደህንነት · ቡድናዊነት · ተጠያቂነት · ዘላቂነት · ቀጣይ ማሻሻያ",
  "about.time.h2a": "የለውጥ",
  "about.time.h2b": "የጊዜ ሰሌዳ።",
  "about.time.r1.t": "የተመሠረተ",
  "about.time.r1.d": "የቀድሞው JTO በDDPC ስር ከተዋቀረ በኋላ የተመሠረተ።",
  "about.time.r2.y": "1999–2025",
  "about.time.r2.t": "የሁለት አስርት ዓመታት እድገት",
  "about.time.r2.d": "በመንግስት፣ በተባበሩት መንግስታት፣ በNGO እና በዲፕሎማቲክ የፍሊት አገልግሎት አስተማማኝ ስም ገንብቷል።",
  "about.time.r3.t": "ስትራቴጂካዊ ለውጥ",
  "about.time.r3.d": "80% የድርሻ በአቶ ዘላለም ለሚ ተገዛ፤ የአስተዳደር፣ ስርዓቶች እና EV አቅም ዘመናዊነት ይጀምራል።",
  "about.lead.h2": "አመራር።",
  "about.lead.label": "ዋና ባለ ድርሻ — 80%",
  "about.lead.name": "አቶ ዘላለም ለሚ",
  "about.lead.p": "ከሁለት አስርት ዓመታት በላይ ልምድ ያለው የተሽከርካሪ ኢንዱስትሪ ባለ ሀብት፣ የAFS ዘመናዊነት ፕሮግራምን ይመራል — አስተዳደርን በማጠናከር፣ ብቁ ባለሙያዎችን በማዋሃድ እና በዘርፉ ስትራቴጂካዊ ሽርክናዎችን በማስፋፋት።",
  "about.pill.h2a": "አክሰለሬት ስትራቴጂ —",
  "about.pill.h2b": "ስድስት ምሰሶዎች።",
  "about.pill.01.t": "ሰዎች እና ቴክኒካል ብቃት", "about.pill.01.d": "ቀጣይ ሙያዊ ማዳበር እና ቴክኒካል ማረጋገጫ።",
  "about.pill.02.t": "ፈጠራ እና ዲጂታል ለውጥ", "about.pill.02.d": "የላቀ ምርመራ፣ ዲጂታል የፍሊት ስርዓቶች፣ EV አገልግሎቶች።",
  "about.pill.03.t": "የስራ ብቃት", "about.pill.03.d": "የተመሳሰሉ ሂደቶች እና የጥራት ማረጋገጫ።",
  "about.pill.04.t": "ደንበኛ-ተኮር አገልግሎት", "about.pill.04.d": "ለእያንዳንዱ ደንበኛ የስራ ፍላጎት የተስተካከሉ መፍትሔዎች።",
  "about.pill.05.t": "ስትራቴጂካዊ ሽርክናዎች", "about.pill.05.d": "ከመንግስት፣ ከUN፣ ከኢንሹራንስ አድራጊዎች እና አምራቾች ጋር ግንኙነትን ማጠናከር።",
  "about.pill.06.t": "ዘላቂነት እና የወደፊት ተንቀሳቃሽነት", "about.pill.06.d": "EV ዝግጁነት እና ኃይል ቆጣቢ አረንጓዴ ተንቀሳቃሽነት ኢንቨስትመንት።",

  // Services
  "services.hero.label": "አገልግሎቶች",
  "services.hero.h1a": "ፍሊትዎ የሚያስፈልገው",
  "services.hero.h1b": "እያንዳንዱ አገልግሎት።",
  "services.r1.label": "የፍሊት አስተዳደር", "services.r1.t1": "ከመጀመሪያ እስከ መጨረሻ", "services.r1.t2": "የፍሊት ዑደት።", "services.r1.body": "የፍሊት ምርመራ፣ ሪፖርት እና የአፈጻጸም ክትትል የንብረት ዕድሜን ያራዝማል እና ወጪን ይቀንሳል።", "services.r1.cap": "የፍሊት አስተዳደር",
  "services.r2.label": "የመከላከያ ጥገና", "services.r2.t1": "ከመሰበር", "services.r2.t2": "ቀድመው ይሁኑ።", "services.r2.body": "የተያዘ አገልግሎት፣ የፈሳሽ አስተዳደር፣ የፍሬን እና የሱስፔንሽን ምርመራ — በአምራች መርሃ ግብር እና በእውነተኛ ፍሊት አጠቃቀም መሠረት።", "services.r2.cap": "የመከላከያ ጥገና",
  "services.r3.label": "ጥገና", "services.r3.t1": "የማስተካከያ ጥገና፣", "services.r3.t2": "በትክክል የተከናወነ።", "services.r3.body": "ሜካኒካል፣ መዋቅራዊ እና የሞተር ማደስ ስራ በተቆጣጠረ የስራ ካርድ ሂደት ከብዙ ደረጃ የጥራት ምርመራ ጋር።", "services.r3.cap": "ጥገና እና የሞተር ማደስ",
  "services.r4.label": "ምርመራ", "services.r4.t1": "ኮምፒዩተራይዝድ", "services.r4.t2": "ትክክለኝነት።", "services.r4.body": "ዘመናዊ ኤሌክትሮኒክ መመርመሪያዎች እና ተንታኞች ጉድለቶችን በፍጥነት ይለያሉ — ግምትን እና ተደጋጋሚ ጉብኝቶችን ይቀንሳሉ።", "services.r4.cap": "የኤሌክትሪክ እና የኤሌክትሮኒክ ምርመራ",
  "services.r5.label": "አካል እና ቀለም", "services.r5.t1": "መዋቅራዊ ጥገና፣", "services.r5.t2": "የፋብሪካ ማጠናቀቂያ።", "services.r5.body": "የተዘጋ የቀለም መርጨት ክፍሎች እና የፓነል ስራ ገጽታን እና መዋቅራዊ ጥንካሬን ይመልሳል።", "services.r5.cap": "አካል እና ቀለም",
  "services.r6.label": "የEV አገልግሎት", "services.r6.t1": "ለኤሌክትሪክ", "services.r6.t2": "ፍሊት ዝግጁ።", "services.r6.body": "የተለየ የEV ጥገና ማዕከል ከከፍተኛ ቮልቴጅ መሳሪያዎች እና ልዩ የባትሪ እና የኤሌክትሪክ ምርመራ ጋር።", "services.r6.cap": "የEV ጥገና ማዕከል",

  // Industries
  "ind.hero.label": "ኢንዱስትሪዎች",
  "ind.hero.h1a": "ስድስት ዘርፎች።",
  "ind.hero.h1b": "አንድ ተጠያቂ አውደ ጥገና።",
  "ind.hero.lead": "ከUN ሞተር ፑል እስከ ኮንስትራክሽን ፍሊት — AFS ለእያንዳንዱ ዘርፍ የተስተካከሉ ልዩ የአገልግሎት ደረጃዎችን ያቀርባል።",
  "ind.sectorLabel": "ዘርፍ",
  "ind.s1.tag": "መንግስት", "ind.s1.t1": "የመንግስት", "ind.s1.t2": "ፍሊቶች።", "ind.s1.lead": "የፌደራል እና የክልል አስተዳደሮች ዝግጁ የሚደረጉ።", "ind.s1.body": "ከሚኒስቴር ሞተር ፑል እስከ ክልል የትራንስፖርት ቢሮዎች፣ የመንግስት ተሽከርካሪዎችን በጥብቅ ተከትሎ፣ ኦዲት-ዝግጁ ሪፖርት እና በሚገመት አገልግሎት መርሃ ግብር እናጠግናለን።", "ind.s1.b1": "የሚኒስቴር ሞተር ፑል", "ind.s1.b2": "የክልል ቢሮዎች", "ind.s1.b3": "የከተማ አገልግሎቶች", "ind.s1.m1": "የስራ ጊዜ SLA", "ind.s1.m2": "አማካይ TAT",
  "ind.s2.tag": "NGO", "ind.s2.t1": "የልማት", "ind.s2.t2": "አጋሮች።", "ind.s2.lead": "ለሰብዓዊ ስራዎች አስተማማኝ በሜዳ የተፈተነ ጥገና።", "ind.s2.body": "በሜዳ ጥቅም ላይ የሚውሉ 4x4 እና ከባድ ተሽከርካሪዎችን እናገለግላለን — ከዕቃ ተገኝነት፣ የመንገድ-ብቁነት ማረጋገጫ እና በ Toyota፣ Nissan፣ Land Rover እና Isuzu የሰለጠኑ ቴክኒካል ቡድኖች ጋር።", "ind.s2.b1": "4×4 የሜዳ ተሽከርካሪዎች", "ind.s2.b2": "የመንገድ-ብቁነት ማረጋገጫ", "ind.s2.b3": "አገር አቀፍ አገልግሎት", "ind.s2.m1": "NGO ደንበኞች", "ind.s2.m2": "ለሜዳ ዝግጁ",
  "ind.s3.tag": "የUN ኤጀንሲዎች", "ind.s3.t1": "ዓለም አቀፍ", "ind.s3.t2": "ልማት።", "ind.s3.lead": "ለዓለም አቀፍ የአገልግሎት እና የደህንነት ደረጃዎች ጥብቅ ተከትሎ።", "ind.s3.body": "በUNDP፣ UNICEF፣ WHO፣ WFP እና FAO የታመነ — ሂደቶቻችን ከዓለም አቀፍ ግዢ፣ ከHSE እና ከሪፖርት መስፈርቶች ጋር ይዛመዳሉ፣ በዲጂታል የስራ ካርዶች እና ተከታታይ የዕቃ አቅርቦት የተደገፉ።", "ind.s3.b1": "ዲጂታል የስራ ካርዶች", "ind.s3.b2": "ተከታታይ OEM ዕቃዎች", "ind.s3.b3": "HSE-ተከትሎ አውደ ጥገና", "ind.s3.m1": "የUN ኤጀንሲዎች", "ind.s3.m2": "የISO ተስማምቶ",
  "ind.s4.tag": "ኢንሹራንስ", "ind.s4.t1": "ክሌም እና", "ind.s4.t2": "ማረጋገጫ።", "ind.s4.lead": "ግልፅ፣ ዲጂታይዝድ የወጪ ግምት በፈጣን አገልግሎት።", "ind.s4.body": "በኢትዮጵያ ቀዳሚ የኢንሹራንስ አድራጊዎች ለአደጋ ጥገና የተፈቀደ፣ የተዘረዘሩ ግምቶች፣ ፎቶግራፍ ማስረጃ እና የተዋቀረ የክሌም ሂደት እናቀርባለን — የዑደት ጊዜ እና የክርክር መጠን በመቀነስ።", "ind.s4.b1": "የተዘረዘሩ ዲጂታል ግምቶች", "ind.s4.b2": "የፎቶግራፍ ክሌም ማስረጃ", "ind.s4.b3": "የተፈቀደ አካል እና ቀለም", "ind.s4.m1": "ኢንሹራንስ አድራጊዎች", "ind.s4.m2": "የግምት ዑደት",
  "ind.s5.tag": "ኮርፖሬት", "ind.s5.t1": "ኮሜርሺያል እና", "ind.s5.t2": "ሎጂስቲክስ።", "ind.s5.lead": "የአቅርቦት ሰንሰለት መስተጓጎልን የሚከላከል የተያዘ ጥገና።", "ind.s5.body": "የስርጭት ፍሊት፣ የሽያጭ ፍሊት እና የሎጂስቲክስ አድራጊዎች ከመጀመሪያ እስከ መጨረሻ በምንመራው የመከላከያ መርሃ ግብር ላይ ይሠራሉ — ከማይሌጅ ክትትል እስከ ጎማ፣ ፍሬን እና ድራይቭ ትሬን የዑደት እቅድ።", "ind.s5.b1": "የስርጭት ፍሊት", "ind.s5.b2": "የሽያጭ ፍሊት", "ind.s5.b3": "የቀዝቃዛ ሰንሰለት ሎጂስቲክስ", "ind.s5.m1": "ተሽከርካሪ / ዓመት", "ind.s5.m2": "PM ተከትሎ",
  "ind.s6.tag": "ኮንስትራክሽን", "ind.s6.t1": "ኢንዱስትሪያዊ", "ind.s6.t2": "ስራዎች።", "ind.s6.lead": "ለከባድ የሜዳ ሁኔታዎች ከባድ ጥገና።", "ind.s6.body": "የናፍታ ቀላል ጭነት አገልግሎት፣ የሃይድሮሊክ ስርዓት ምርመራ፣ የቻሲስ ብየዳ እና በኢትዮጵያ አስቸጋሪ መሬቶች ላይ ለሚሰሩ ኮንስትራክሽን፣ ማዕድን እና መሠረተ ልማት አድራጊዎች መዋቅራዊ ጥገና።", "ind.s6.b1": "የናፍታ ቀላል ጭነት አገልግሎት", "ind.s6.b2": "የቻሲስ እና መዋቅራዊ ብየዳ", "ind.s6.b3": "የሃይድሮሊክ ምርመራ", "ind.s6.m1": "የጭነት ቦታዎች", "ind.s6.m2": "የብየዳ አቅም",
  "ind.cap.label": "የዘርፍ-ተሻጋሪ አቅም",
  "ind.cap.h2a": "አንድ አውደ ጥገና።",
  "ind.cap.h2b": "እያንዳንዱ የፍሊት ዓይነት።",
  "ind.cap.desc": "የዲፕሎማቲክ ሴዳን፣ የሰብዓዊ 4×4፣ የተጠበቀ የአደጋ መልሶ ማገገሚያ ወይም የኮንስትራክሽን ጭነት ቢሆን — ተመሳሳይ የምህንድስና ተግሣጽ፣ ተመሳሳይ የዲጂታል የስራ ካርድ ሂደት።",
  "ind.cap.s1": "ፍሊት ያገለገሉ ዓመታት",
  "ind.cap.s2": "ተሽከርካሪ በዓመት",
  "ind.cap.s3": "ተቋማዊ ደንበኞች",
  "ind.cap.s4": "የተቋም ስፋት",
  "ind.cap.talk": "የፍሊት ቡድናችንን ያናግሩ ↗",
  "ind.cap.explore": "አቅሞችን ይዳስሱ",

  // Facilities
  "fac.hero.label": "ተቋማት",
  "fac.hero.h1a": "3,000+ ካሬ ሜትር የ",
  "fac.hero.h1b": "የተነደፈ አቅም።",
  "fac.hero.lead": "ጎተራ፣ ንፋስ ስልክ ላፍቶ ክፍለ ከተማ፣ አዲስ አበባ።",
  "fac.show.h2a": "የተቋም",
  "fac.show.h2b": "ማሳያ።",
  "fac.eq.h2a": "ዋና",
  "fac.eq.h2b": "መሳሪያዎች።",
  "fac.eq.01.t": "ባለ አራት ልጥፍ ማንሻዎች", "fac.eq.01.d": "8,000–12,000 ፓውንድ አቅም · 4 ቦታዎች እና የምርመራ ጉድጓዶች",
  "fac.eq.02.t": "ኤሌክትሮኒክ መመርመሪያዎች", "fac.eq.02.d": "Autoboss እና Launch (2021) · 23 ክፍሎች",
  "fac.eq.03.t": "የብየዳ ማሽኖች", "fac.eq.03.d": "ለመዋቅራዊ እና ለአካል ጥገና 3 ክፍሎች",
  "fac.eq.04.t": "ማልቲሜትር እና ተንታኞች", "fac.eq.04.d": "3 ኤሌክትሮኒክ የምርመራ ተንታኞች",
  "fac.eq.05.t": "የደህንነት ስርዓቶች", "fac.eq.05.d": "የእሳት ማጥፊያዎች፣ የመጀመሪያ እርዳታ ኪት፣ የእሳት ብርድ ልብሶች",

  // Sustainability
  "sus.hero.label": "ዘላቂነት",
  "sus.hero.h1a": "አስተማማኝ ስራዎች።",
  "sus.hero.h1b": "ዘላቂ እድገት።",
  "sus.r.01.t": "የጤና፣ ደህንነት እና አካባቢ (HSE) ፖሊሲ", "sus.r.01.d": "የPPE መመሪያዎች፣ የተነደፉ የደህንነት ዞኖች እና በተቋሙ ውስጥ ቀጣይ የአደጋ ግምገማ።",
  "sus.r.02.t": "የአካባቢ ጥበቃ ፖሊሲ", "sus.r.02.d": "የተጠቀሙ ዘይት፣ ቅባቶች እና እርሳስ-አሲድ ባትሪዎችን በአግባቡ መጣል፤ የተቆጣጠረ የኬሚካል ማከማቻ።",
  "sus.r.03.t": "የቆሻሻ አስተዳደር", "sus.r.03.d": "የቆሻሻ መለያየት፣ የመፍሰስ መከላከል እና የፅዱ አውደ ጥገና አስተዳደር።",
  "sus.r.04.t": "የEV ዝግጁነት", "sus.r.04.d": "ከፍተኛ ቮልቴጅ መሳሪያዎች፣ የተለዩ የEV ጥገና ቦታዎች እና የባትሪ-ደህንነት ስልጠና።",
  "sus.r.05.t": "የዘላቂነት ቁርጠኝነት", "sus.r.05.d": "ኃይል ቆጣቢ መሳሪያዎች፣ በዲጂታል የስራ ካርድ ክትትል የተቀነሰ የወረቀት ጥገኝነት።",

  // Clients
  "cli.hero.label": "ደንበኞች",
  "cli.hero.h1a": "AFSን",
  "cli.hero.h1b": "የሚያምኑ ተቋማት።",
  "cli.trust.label": "የታመኑ አጋሮች",
  "cli.trust.h2a": "40+ ተቋማት በ",
  "cli.trust.h2b": "UN፣ መንግስት፣ NGO እና ኢንሹራንስ ዘርፎች።",
  "cli.note": "እያንዳንዱ ስም ምልክት በUN ድርጅቶች፣ በዲፕሎማሲያዊ ተልእኮዎች፣ በNGO፣ በኢንሹራንስ እና በመንግስት ዘርፎች ረጅም ጊዜ የቆየ ተቋማዊ ግንኙነትን ይወክላል።",
  "cli.trust.count": "ተቋማዊ አጋሮች",

  // Contact
  "con.hero.label": "ያግኙን",
  "con.hero.h1a": "ምርመራ",
  "con.hero.h1b": "ይመዝገቡ።",
  "con.hero.lead": "የAFS ቡድንን ያግኙ።",
  "con.form.label": "መልእክት ይላኩ",
  "con.form.name": "ሙሉ ስም", "con.form.namePh": "ስምዎ",
  "con.form.org": "ድርጅት", "con.form.orgPh": "ኩባንያ / ኤጀንሲ",
  "con.form.email": "ኢሜይል", "con.form.emailPh": "you@organization.org",
  "con.form.msg": "መልእክት", "con.form.msgPh": "ስለ ፍሊት ፍላጎትዎ ይንገሩን",
  "con.form.submit": "ጥያቄ ላክ",
  "con.form.thanks": "እናመሰግናለን — በቅርቡ እናገኝዎታለን።",
  "con.info.label": "ያግኙን",
  "con.info.location": "አካባቢ",
  "con.info.locationV": "ጎተራ፣ ንፋስ ስልክ ላፍቶ ክፍለ ከተማ፣ አዲስ አበባ፣ ኢትዮጵያ",
  "con.info.phone": "ስልክ",
  "con.info.email": "ኢሜይል",
  "con.info.hours": "የአውደ ጥገና ሰዓቶች",
  "con.info.hoursV": "ሰኞ–ቅዳሜ፣ 8:00 ጠዋት – 6:00 ማታ · አስቸኳይ 24/7",
  "con.info.map": "ጎተራ፣ አዲስ አበባ",

  // Footer
  "foot.desc": "ከ1999 ጀምሮ የኢትዮጵያ ቀዳሚ የተሽከርካሪ ፍሊት አስተዳደር እና ቴክኒካል አገልግሎት አቅራቢ።",
  "foot.company": "ኩባንያ",
  "foot.services": "አገልግሎቶች",
  "foot.contact": "ያግኙን",
  "foot.link.about": "ስለ እኛ",
  "foot.link.sustainability": "ዘላቂነት",
  "foot.link.clients": "ደንበኞች",
  "foot.link.fleet": "የፍሊት አስተዳደር",
  "foot.link.ev": "የEV ጥገና",
  "foot.link.facilities": "ተቋማት",
  "foot.addr1": "ጎተራ፣ ንፋስ ስልክ ላፍቶ",
  "foot.addr2": "አዲስ አበባ፣ ኢትዮጵያ",
  "foot.copyright": "© 2026 AFS International PLC. መብቱ በህግ የተጠበቀ ነው።",
  "foot.est": "የተመሠረተ 1999 · አዲስ አበባ",
};

const DICTS: Record<Lang, Dict> = { en: EN, am: AM };

type Ctx = {
  lang: Lang;
  setLang: (l: Lang) => void;
  theme: Theme;
  setTheme: (t: Theme) => void;
  toggleTheme: () => void;
  t: (key: string) => string;
};

const SiteCtx = createContext<Ctx | null>(null);

export function SiteProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");
  const [theme, setThemeState] = useState<Theme>("light");

  useEffect(() => {
    try {
      const l = localStorage.getItem("afs.lang") as Lang | null;
      const t = localStorage.getItem("afs.theme") as Theme | null;
      if (l === "en" || l === "am") setLangState(l);
      if (t === "light" || t === "dark") setThemeState(t);
    } catch { /* noop */ }
  }, []);

  useEffect(() => {
    document.body.classList.toggle("dark", theme === "dark");
    document.body.classList.add("corporate-theme");
    try { localStorage.setItem("afs.theme", theme); } catch { /* noop */ }
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = lang === "am" ? "am" : "en";
    try { localStorage.setItem("afs.lang", lang); } catch { /* noop */ }
  }, [lang]);

  const value: Ctx = {
    lang,
    setLang: setLangState,
    theme,
    setTheme: setThemeState,
    toggleTheme: () => setThemeState((v) => (v === "light" ? "dark" : "light")),
    t: (key) => DICTS[lang][key] ?? EN[key] ?? key,
  };

  return <SiteCtx.Provider value={value}>{children}</SiteCtx.Provider>;
}

export function useSite() {
  const c = useContext(SiteCtx);
  if (!c) throw new Error("useSite must be used within SiteProvider");
  return c;
}
